name: Pickleball Reservation

on:
  schedule:
    - cron: "58 15 * * 5" # Runs every Friday at 7:58 AM PST (15:58 UTC)
  workflow_dispatch: # Allows manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [shinichi, yuki] # Define environments
    environment: ${{ matrix.environment }} # Set the environment dynamically

    steps:
      - name: Set Timezone to Pacific Time
        run: sudo timedatectl set-timezone America/Los_Angeles

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Chromium
        run: npx playwright install chromium

      - name: Run the script
        run: node pickleball_reservation.js
        env:
          WEBTRAC_USERNAME: ${{ secrets.WEBTRAC_USERNAME }}
          WEBTRAC_PASSWORD: ${{ secrets.WEBTRAC_PASSWORD }}
          FAMILY_MEMBER: ${{ secrets.FAMILY_MEMBER }}
          NO_RESERVATION: ${{ vars.NO_RESERVATION }}
          DAYS_AHEAD: ${{vars.DAYS_AHEAD}}
          COURT: ${{ vars.COURT }}
          MAX_WARNING_RETRIES: ${{ vars.MAX_WARNING_RETRIES }}
          RELOAD_INTERVAL: ${{ vars.RELOAD_INTERVAL }}
          HEADLESS: true # Playwright doesn't work in non-headless mode

      - name: Upload Screenshot
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: screenshot-${{ matrix.environment }}.png
