name: Pickleball Reservation

on:
  schedule:
    - cron: "58 15 * * 5" # Runs every Friday at 7:58 AM PST (15:58 UTC)
  workflow_dispatch: # Allows manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest
    environment: shinichi

    steps:
      - name: Set Timezone to Pacific Time
        run: sudo timedatectl set-timezone America/Los_Angeles

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Install Chromium
        run: npx playwright install chromium

      - name: Run the script
        run: node pickleball_reservation.js
        env:
          HEADLESS: true # Playwright doesn't work in non-headless mode
